# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

mr:
  instance-type: prim
  task-reset-timeout-multiplier: 4.0
  task-warning-timeout-multiplier: 2.0
  tasks:
    prim-health-analysis-task:
      enabled: true
      delay: PT10M
    sec-health-analysis-task:
      enabled: false
      delay: PT10M
    resolution-send-task:
      enabled: true
      delay: PT10M
      timeout: PT30M
      max-retries: 10
      initial-retry-delay: PT10M
      max-retry-delay: P1D
    collect-analyst-info-task:
      enabled: true
      delay: PT10M
    send-alerts-task:
      enabled: true
      delay: PT10M
    alert-template-reconciliation-task:
      enabled: true
      delay: PT1H
azure:
  cosmosdb:
    default-ttl: P1827D
  dfp:
    purchase-status-event-url: https://${CLIENT_TENANT_SHORT_NAME}-${CLIENT_TENANT_ID}.api.dfp.dynamics.com/v1.0/merchantservices/events/PurchaseStatus
  graph-api:
    role-assignments-url: https://graph.microsoft.com/v1.0/servicePrincipals/${DFP_SP_ID}/appRoleAssignedTo
    user-role-assignments-url-template: https://graph.microsoft.com/v1.0/users/#user_id#/appRoleAssignments?$filter=resourceId eq ${DFP_SP_ID}
    users-url: https://graph.microsoft.com/v1.0/users
    user-url-template: https://graph.microsoft.com/v1.0/users/#user_id#
    app-service-principal-url: https://graph.microsoft.com/v1.0/servicePrincipals/${DFP_SP_ID}
    user-photo-url-template: https://graph.microsoft.com/beta/users/#user_id#/photo/$value
    timeout: PT5S
    retries: 2
    role-mapping:
      ManualReviewFraudManager: ADMIN_MANAGER
      ManualReviewSeniorAnalyst: SENIOR_ANALYST
      ManualReviewAnalyst: ANALYST
  dfp-auth:
    token-cache-size: 500
    token-cache-retention: PT10M
  event-hub:
    checkpoint-interval: PT3M
    sending-timeout: PT10M
    sending-retries: 3
    health-check-ttl: PT24H
    health-check-batch-size: 5
    health-check-allowed-delay: PT60M

swagger:
  token-url: https://login.microsoftonline.com/${CLIENT_TENANT_ID}/oauth2/v2.0/token

spring:
  security:
    oauth2:
      client:
        registration:
          azure-graph-api:
            scope: https://graph.microsoft.com/.default
          azure-dfp-api:
            scope: https://api.dfp.microsoft.com/.default
        provider:
          azure-graph-api:
            token-uri: https://login.microsoftonline.com/${CLIENT_TENANT_ID}/oauth2/v2.0/token
          azure-dfp-api:
            token-uri: https://login.microsoftonline.com/${CLIENT_TENANT_ID}/oauth2/v2.0/token

resilience4j.retry:
  instances:
    cosmosOptimisticUpdate:
      maxRetryAttempts: 3
      waitDuration: 100ms
