mr:
  task-reset-timeout-multiplier: 4.0
  task-warning-timeout-multiplier: 2.0
  tasks:
    fail-fast-healthcheck-task:
      delay: PT10M
    resolution-send-task:
      delay: PT1M
      timeout: PT5M
      max-retries: 10
      initial-retry-delay: PT10M
      max-retry-delay: P1D
    collect-analyst-info-task:
      delay: PT10M
    send-alerts-task:
      delay: PT1M
      timeout: PT5M
    alert-template-reconciliation-task:
      delay: PT10M
azure:
  cosmosdb:
    default-ttl: P1827D
  dfp:
    purchase-status-event-url: https://${TENANT_SHORT_NAME}-${TENANT_ID}.api.dfp.dynamics-int.com/v1.0/merchantservices/events/PurchaseStatus
  graph-api:
    role-assignments-url: https://graph.microsoft.com/v1.0/servicePrincipals/${DFP_SP_ID}/appRoleAssignedTo
    user-role-assignments-url-template: https://graph.microsoft.com/v1.0/users/#user_id#/appRoleAssignments?$filter=resourceId eq ${DFP_SP_ID}
    users-url: https://graph.microsoft.com/v1.0/users
    user-url-template: https://graph.microsoft.com/v1.0/users/#user_id#
    app-service-principal-url: https://graph.microsoft.com/v1.0/servicePrincipals/${DFP_SP_ID}
    user-photo-url-template: https://graph.microsoft.com/beta/users/#user_id#/photo/$value
    role-mapping:
      ManualReviewFraudManager: ADMIN_MANAGER
      ManualReviewSeniorAnalyst: SENIOR_ANALYST
      ManualReviewAnalyst: ANALYST
      Sandbox_ManualReviewFraudManager: ADMIN_MANAGER
      Sandbox_ManualReviewSeniorAnalyst: SENIOR_ANALYST
      Sandbox_ManualReviewAnalyst: ANALYST
  dfp-auth:
    token-cache-size: 500
    token-cache-retention: PT10M
  event-hub:
    checkpoint-interval: PT3M
    consumer-error-threshold: 5
    producerer-error-threshold: 5

swagger:
  # the https://cors-anywhere.herokuapp.com/ prefix is only for dev environments
  token-url: https://cors-anywhere.herokuapp.com/https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token

spring:
  security:
    oauth2:
      client:
        registration:
          azure-graph-api:
            scope: https://graph.microsoft.com/.default
          azure-dfp-api:
            scope: https://api.dfp.microsoft-int.com/.default
        provider:
          azure-graph-api:
            token-uri: https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token
          azure-dfp-api:
            token-uri: https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token

resilience4j.retry:
  instances:
    cosmosOptimisticUpdate:
      maxRetryAttempts: 3
      waitDuration: 100ms
