# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

mr:
  instance-type: sec
  tasks:
    prim-health-analysis-task:
      enabled: false
    sec-health-analysis-task:
      enabled: true
azure:
  event-hub:
    connection-string: ${spring-cloud-azure-eventhub-secondary-connection-string:${EVENT_HUB_CONNECTION_STRING}}
    checkpoint-connection-string: DefaultEndpointsProtocol=https;AccountName=${EVENT_HUB_OFFSET_STORAGE_NAME};AccountKey=${spring-cloud-azure-eventhub-checkpoint-secondary-access-key:${EVENT_HUB_OFFSET_STORAGE_KEY}};EndpointSuffix=core.windows.net
