server:
  port: 8080

mr:
  task-reset-timeout-multiplier: 4.0
  task-warning-timeout-multiplier: 2.0
  tasks:
    residual-queue-reconciliation-task:
      enabled: true
      delay: PT10M
    queue-size-calculation-task:
      enabled: true
      delay: PT10M
    overall-size-calculation-task:
      enabled: true
      delay: PT10M
    item-assignment-reconciliation-task:
      enabled: true
      delay: PT1M
      timeout: PT5M
      comprehensive-check:
        period: PT30M
      partial-check:
        observed-period: PT5M
    item-unlock-task:
      enabled: true
      delay: PT1M
    item-enrichment-task:
      enabled: true
      delay: PT1M
      timeout: PT5M
      enrichment-delay: PT30S
    dictionary-reconciliation-task:
      enabled: true
      delay: PT1H
    queue-assignment-reconciliation-task:
      enabled: true
      delay: PT10M
  items:
    unlock-timeout: PT5M
    near-to-timeout: PT1M
    near-to-sla: P2D
  task-executor:
    corepool-size: 5
    max-pool-size: 10
    queue-capacity: 25
    timeout-seconds: PT5M
  dictionary:
    ttl: P14D

logging:
  group:
    azures: com.microsoft.azure.spring.autoconfigure.aad, com.azure.messaging.eventhubs.PartitionBasedLoadBalancer
  level:
    azures: WARN
azure:
  cosmosdb:
    uri: ${COSMOSDB_ENDPOINT}
    key: ${azure-cosmosdb-key:${COSMOSDB_KEY}}
    database: QueuesDB
    default-ttl: P183D
    consistency-level: SESSION
    allow-telemetry: false
    populate-query-metrics: false
  activedirectory:
    client-id: ${CLIENT_ID}
    session-stateless: true
  graph-api:
    role-assignments-url: https://graph.microsoft.com/v1.0/servicePrincipals/${DFP_SP_ID}/appRoleAssignedTo
    user-role-assignments-url-template: https://graph.microsoft.com/v1.0/users/#user_id#/appRoleAssignments?$filter=resourceId eq ${DFP_SP_ID}
    users-url: https://graph.microsoft.com/v1.0/users
    user-url-template: https://graph.microsoft.com/v1.0/users/#user_id#
    app-service-principal-url: https://graph.microsoft.com/v1.0/servicePrincipals/${DFP_SP_ID}
    user-photo-url-template: https://graph.microsoft.com/beta/users/#user_id#/photo/$value
    role-mapping:
      ManualReviewFraudManager: ADMIN_MANAGER
      ManualReviewSeniorAnalyst: SENIOR_ANALYST
      ManualReviewAnalyst: ANALYST
      Sandbox_ManualReviewFraudManager: ADMIN_MANAGER
      Sandbox_ManualReviewSeniorAnalyst: SENIOR_ANALYST
      Sandbox_ManualReviewAnalyst: ANALYST
  dfp:
    graph-explorer-url: https://${TENANT_SHORT_NAME}-${TENANT_ID}.api.dfp.dynamics-int.com/knowledgegateway/customersupport/v1.0/explorer/traversal
    purchase-event-url: https://intz.api.dfp.dynamics-int.com/v1.0/merchantservices/events/Purchase
    bank-event-url: https://intz.api.dfp.dynamics-int.com/v1.0/merchantservices/events/BankEvent
  dfp-auth:
    token-cache-size: 500
    token-cache-retention: PT10M
  keyvault:
    # Use managed identity to authenticate
    enabled: true
    uri: ${KEYVAULT_ENDPOINT}

swagger:
  auth-url: https://login.microsoftonline.com/${TENANT_ID}/oauth2/authorize?resource=${CLIENT_ID}

spring:
  application:
    name: mr-queues
  security:
    oauth2:
      client:
        registration:
          azure-graph-api:
            client-id: ${CLIENT_ID}
            client-secret: ${client-secret:${CLIENT_SECRET}}
            authorization-grant-type: client_credentials
            scope: https://graph.microsoft.com/.default
          azure-dfp-api:
            client-id: ${CLIENT_ID}
            client-secret:  ${client-secret:${CLIENT_SECRET}}
            authorization-grant-type: client_credentials
            scope: https://api.dfp.microsoft-int.com/.default
        provider:
          azure-graph-api:
            token-uri: https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token
          azure-dfp-api:
            token-uri: https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token
  cloud:
    azure:
      eventhub:
        connection-string: ${spring-cloud-azure-eventhub-connection-string:${EVENT_HUB_CONNECTION_STRING}}
        checkpoint-storage-account: ${EVENT_HUB_OFFSET_STORAGE_NAME}
        checkpoint-access-key: ${spring-cloud-azure-eventhub-checkpoint-access-key:${EVENT_HUB_OFFSET_STORAGE_KEY}}
        bindings:
          input:
            consumer:
              checkpoint-mode: MANUAL
    stream:
      eventhub:
        bindings:
          #          WARNING!!! Don't use checkpoint-mode: TIME and checkpoint-mode: BATCH
          #          because of https://github.com/microsoft/spring-cloud-azure/issues/755
          #          and https://github.com/microsoft/spring-cloud-azure/commit/ac6fef38ac99c8a843227d1d785eaf30584ada67#diff-ba40671ca26e6582be133cddb4973ab8
          dfp-input:
            consumer:
              start-position: EARLIEST
              checkpoint-mode: RECORD
      bindings:
        dfp-input:
          destination: dfp-hub
          group: ${spring.application.name}
        item-lock-event-output:
          destination: item-lock-event-hub
        item-label-event-output:
          destination: item-label-event-hub
        item-resolution-event-output:
          destination: item-resolution-event-hub
        item-assignment-event-output:
          destination: item-assignment-event-hub
        mock-dfp-output:
          destination: dfp-hub
        queue-size-event-output:
          destination: queue-size-event-hub
        queue-update-event-output:
          destination: queue-update-event-hub
        overall-size-event-output:
          destination: overall-size-event-hub
  aop:
    proxyTargetClass: true

resilience4j.retry:
  instances:
    cosmosOptimisticCapture:
      maxRetryAttempts: 30
      waitDuration: 10ms
      retryExceptions:
        - com.microsoft.azure.spring.data.cosmosdb.exception.CosmosDBAccessException
        - com.azure.data.cosmos.CosmosClientException
    cosmosOptimisticUpdate:
      maxRetryAttempts: 3
      waitDuration: 100ms
      retryExceptions:
        - com.microsoft.azure.spring.data.cosmosdb.exception.CosmosDBAccessException
        - com.azure.data.cosmos.CosmosClientException
