spring:
  cloud:
    azure:
      eventhub:
        connection-string: ${spring-cloud-azure-eventhub-secondary-connection-string:${EVENT_HUB_CONNECTION_STRING}}
        checkpoint-access-key: ${spring-cloud-azure-eventhub-checkpoint-secondary-access-key:${EVENT_HUB_OFFSET_STORAGE_KEY}}