# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

mr:
  tasks:
    resolution-sending-task:
      enabled: false
    prim-health-analysis-task:
      enabled: false
    sec-health-analysis-task:
      enabled: false
    residual-queue-reconciliation-task:
      enabled: false
    queue-size-calculation-task:
      enabled: false
    overall-size-calculation-task:
      enabled: false
    item-assignment-reconciliation-task:
      enabled: false
    item-unlock-task:
      enabled: false
    dictionary-reconciliation-task:
      enabled: false
    item-enrichment-task:
      enabled: false
    queue-assignment-reconciliation-task:
      enabled: false

logging:
  level:
    com:
      griddynamics: TRACE

azure:
  keyvault:
    # Use service principle to authenticate locally
    enabled: true
    client-key: ${CLIENT_SECRET}
    client-id: ${CLIENT_ID}
    tenant-id: ${CLIENT_TENANT_ID}
